apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: xtreamly-api
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb-ip"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: xtreamly-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: web
          image: 893048150390.dkr.ecr.eu-central-1.amazonaws.com/xtreamly-api/api:latest
          ports:
            - containerPort: 8000
          env:
            - name: 'SHARED_DATA_PATH'
              value: '/mnt/shared'
          envFrom:
            - secretRef:
                name: fastapi-secret
          resources:
            requests:
              cpu: "2000m"
              memory: "4000Mi"
            limits:
              cpu: "2000m"
              memory: "4000Mi"
          volumeMounts:
            - name: efs-volume
              mountPath: /mnt/shared
      volumes:
        - name: efs-volume
          persistentVolumeClaim:
            claimName: inference-data-claim
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-hpa
  namespace: xtreamly-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api
  minReplicas: 1
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
